{"name": "Проверка получения ошибки при создании юзера-дубликата", "status": "passed", "steps": [{"name": "Регистрируем нового пользователя с определенными параметрами", "status": "passed", "parameters": [{"name": "email", "value": "'hzgpx@hnaih.hbenf'"}, {"name": "password", "value": "None"}, {"name": "name", "value": "None"}], "start": 1712518195565, "stop": 1712518195840}, {"name": "Проверяем что в ответе StatusCode:403 и в теле ответа success:False", "status": "passed", "start": 1712518195840, "stop": 1712518195840}], "start": 1712518195565, "stop": 1712518195843, "uuid": "b698ea91-7d1a-458b-87c1-17d7788b3161", "historyId": "7988e64f879fb5bf45c86b04f9796b9b", "testCaseId": "7988e64f879fb5bf45c86b04f9796b9b", "fullName": "tests.test_register.TestRegister#test_register_duplicated_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_register"}, {"name": "subSuite", "value": "TestRegister"}, {"name": "host", "value": "pavel"}, {"name": "thread", "value": "19040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_register"}]}